# Megan Conley
# conleyme@onid.oregonstate.edu
# CS344-400
# Homework 6

CC = gcc
CFLAGS = -std=c99 -lm -lrt -D_POSIX_C_SOURCE -Wall -Wshadow -Wunreachable-code -Wredundant-decls -Wmissing-declarations -Wold-style-definition -Wmissing-prototypes -Wdeclaration-after-statement

compute:
	${CC} ${CFLAGS} compute.c -o compute
